version: "3"

services:
  loki:
    image: grafana/loki:1.4.0
    restart: on-failure
    logging:
      driver: none

  promtail:
    build:
      context: .
      dockerfile: promtail-test.Dockerfile
    env_file:
      - docker-compose.test.env
    command: ["--tags", "external", "./..."]
    depends_on:
      - loki
